name: Docker Image CI

on:
  #push:
    #branches:
      #- main
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java
        run: |
          ./gradlew clean flywayMigrate generateJooq
          ./gradlew build

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USER/extractarr:latest --tag $DOCKER_USER/extractarr:$TAG

      - name: Push the Docker image
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Pushing $TAG and latest"
          docker push $DOCKER_USER/extractarr:latest
          docker push $DOCKER_USER/extractarr:$TAG